CREATE TABLE CERBERUS.PLAYER_LOADOUTS(
LOADOUT_ID NUMBER NOT NULL,
OWNING_PLAYER_STEAM_ID VARCHAR2(100) NOT NULL,
LOADOUT_NAME VARCHAR2(100) NOT NULL,
CUSTOM_PRIMARY_ID NUMBER,
CUSTOM_SECONDARY_ID NUMBER
);