Create table CERBERUS.PLAYER_ACCOUNTS(
    STEAM_NAME VARCHAR2(100) NOT NULL,
    STEAM_ID VARCHAR2(100) NOT NULL,
    PLAYER_LEVEL NUMBER NOT NULL,
    BATTLEPASS_LEVEL NUMBER NOT NULL,
    CURRENCY NUMBER NOT NULL,
    IS_LOGGED_IN NUMBER NOT NULL,
    IP_ADDRESS VARCHAR2(30) NOT NULL,
    ACCOUNT_STANDING VARCHAR2(30) NOT NULL,
    BAN_TIMEOUT_DATE DATE,
    BAN_TIMEOUT_TIME TIMESTAMP
);