CREATE TABLE CERBERUS.METADATA_CHARACTER_ABILITIES (	
ABILITY_ID NUMBER,
CHARACTER_ID NUMBER,
ABILITY_NAME VARCHAR2(100),
HEALING NUMBER,
DAMAGE NUMBER,
COOLDOWN NUMBER,
ABILITY_BIND VARCHAR2(20),
ABILITY_TYPE VARCHAR2(20),
ULTIMATE_CHARGE_MODIFIER NUMBER
)