CREATE TABLE "CERBERUS"."METADATA_CHARACTER_SKINS" (	
"SKIN_ID" NUMBER NOT NULL ENABLE, 
CHARACTER_ID NUMBER NOT NULL,
"CHARACTER_NAME" VARCHAR2(75 BYTE) NOT NULL ENABLE, 
"SKIN_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"COST" NUMBER, 
"BASELINE" VARCHAR2(1 BYTE) NOT NULL ENABLE
)