CREATE TABLE CERBERUS.METADATA_GAMEMODES(	
GAME_MODE_ID NUMBER NOT NULL ENABLE, 
ABBREVIATION VARCHAR2(10),
GAME_MODE_NAME VARCHAR2(50),	
DESCRIPTION	VARCHAR2(500),
AMOUNT_OF_TEAMS	NUMBER,
TEAM_SIZE NUMBER,
MAX_PLAYERS	NUMBER,
MAX_SPECTATORS NUMBER,
CAN_JOIN_WITH_FRIENDS VARCHAR2(10)
)