CREATE TABLE "CERBERUS"."ERRORS_OCCURED" (	
"ERROR_RECORD_NUMBER" NUMBER NOT NULL, 
"ERROR_LEVEL" NUMBER NOT NULL, 
"ERROR_NUMBER" NUMBER NOT NULL, 
"STEAM_ID" VARCHAR2(60) NOT NULL,
"DATE" DATE NOT NULL,
"TIMESTAMP" TIMESTAMP NOT NULL
)